apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: repositories.polling.tekton.dev
spec:
  group: polling.tekton.dev
  names:
    kind: Repository
    listKind: RepositoryList
    plural: repositories
    singular: repository
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Repository is the Schema for the repositories API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RepositorySpec defines a repository to poll.
            properties:
              frequency:
                type: string
              pipelineRef:
                description: PipelineRef links to the Pipeline to execute.
                properties:
                  bindings:
                    items:
                      properties:
                        apiversion:
                          description: APIVersion of the binding ref
                          type: string
                        kind:
                          description: Kind can only be provided if Ref is also provided.
                            Defaults to TriggerBinding
                          type: string
                        name:
                          description: Name is the name of the binding param Mutually
                            exclusive with Ref
                          type: string
                        ref:
                          description: Ref is a reference to a TriggerBinding kind.
                            Mutually exclusive with Name
                          type: string
                        spec:
                          description: 'Spec is the deprecated  way of embedding TriggerBindings.
                            TODO(#782): Remove deprecated syntax.'
                          properties:
                            params:
                              description: Params defines the parameter mapping from
                                the given input event.
                              items:
                                description: Param defines a string value to be used
                                  for a ParamSpec with the same name.
                                properties:
                                  name:
                                    type: string
                                  value:
                                    type: string
                                required:
                                - name
                                - value
                                type: object
                              type: array
                          type: object
                        value:
                          description: Value is the value of the binding param. Can
                            contain JSONPath Has to be pointer since "" is a valid
                            value Required if Name is also specified.
                          type: string
                      type: object
                    type: array
                  name:
                    type: string
                  namespace:
                    type: string
                  params:
                    items:
                      properties:
                        expression:
                          type: string
                        name:
                          type: string
                      required:
                      - expression
                      - name
                      type: object
                    type: array
                  template:
                    properties:
                      apiversion:
                        type: string
                      name:
                        description: 'Deprecated: Use Ref instead'
                        type: string
                      ref:
                        type: string
                      spec:
                        description: TriggerTemplateSpec holds the desired state of
                          TriggerTemplate
                        properties:
                          params:
                            items:
                              description: ParamSpec defines an arbitrary named  input
                                whose value can be supplied by a `Param`.
                              properties:
                                default:
                                  description: Default is the value a parameter takes
                                    if no input value via a Param is supplied.
                                  type: string
                                description:
                                  description: Description is a user-facing description
                                    of the parameter that may be used to populate
                                    a UI.
                                  type: string
                                name:
                                  description: Name declares the name by which a parameter
                                    is referenced.
                                  type: string
                              required:
                              - name
                              type: object
                            type: array
                          resourcetemplates:
                            items:
                              description: TriggerResourceTemplate describes a resource
                                to create
                              type: object
                            type: array
                        type: object
                    required:
                    - name
                    type: object
                required:
                - bindings
                - name
                - template
                type: object
              ref:
                type: string
              secretRef:
                description: SecretRef contains the information required to reference
                  a single secret string.
                properties:
                  secretKey:
                    type: string
                  secretName:
                    type: string
                type: object
              type:
                description: RepoType defines the protocol to use to talk to the upstream
                  server.
                enum:
                - github
                - gitlab
                type: string
              url:
                type: string
            required:
            - pipelineRef
            - url
            type: object
          status:
            description: RepositoryStatus defines the observed state of Repository
            properties:
              lastError:
                type: string
              observedGeneration:
                format: int64
                type: integer
              pollStatus:
                description: PollStatus represents the last polled state of the repo.
                properties:
                  etag:
                    type: string
                  ref:
                    type: string
                  sha:
                    type: string
                required:
                - etag
                - ref
                - sha
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
