apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: repositories.polling.tekton.dev
spec:
  group: polling.tekton.dev
  names:
    kind: Repository
    listKind: RepositoryList
    plural: repositories
    singular: repository
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Repository is the Schema for the repositories API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RepositorySpec defines a repository to poll.
            properties:
              auth:
                description: AuthSecret references a secret for authenticating the
                  request.
                properties:
                  key:
                    type: string
                  secretRef:
                    description: SecretReference represents a Secret Reference. It
                      has enough information to retrieve secret in any namespace
                    properties:
                      name:
                        description: Name is unique within a namespace to reference
                          a secret resource.
                        type: string
                      namespace:
                        description: Namespace defines the space within which the
                          secret name must be unique.
                        type: string
                    type: object
                type: object
              frequency:
                type: string
              pipelineRef:
                description: PipelineRef links to the Pipeline to execute.
                properties:
                  bindings:
                    items:
                      description: EventListenerBinding refers to a particular TriggerBinding
                        or ClusterTriggerBindingresource.
                      properties:
                        apiversion:
                          type: string
                        kind:
                          description: Check that EventListener may be validated and
                            defaulted. TriggerBindingKind defines the type of TriggerBinding
                            used by the EventListener.
                          type: string
                        name:
                          type: string
                        ref:
                          type: string
                        spec:
                          description: TriggerBindingSpec defines the desired state
                            of the TriggerBinding.
                          properties:
                            params:
                              description: Params defines the parameter mapping from
                                the given input event.
                              items:
                                description: Param defines a string value to be used
                                  for a ParamSpec with the same name.
                                properties:
                                  name:
                                    type: string
                                  value:
                                    type: string
                                required:
                                - name
                                - value
                                type: object
                              type: array
                          type: object
                      type: object
                    type: array
                  name:
                    type: string
                  namespace:
                    type: string
                  params:
                    items:
                      properties:
                        expression:
                          type: string
                        name:
                          type: string
                      required:
                      - expression
                      - name
                      type: object
                    type: array
                  template:
                    description: EventListenerTemplate refers to a particular TriggerTemplate
                      resource.
                    properties:
                      apiversion:
                        type: string
                      name:
                        type: string
                    required:
                    - name
                    type: object
                required:
                - bindings
                - name
                - template
                type: object
              ref:
                type: string
              type:
                description: RepoType defines the protocol to use to talk to the upstream
                  server.
                enum:
                - github
                - gitlab
                type: string
              url:
                type: string
            required:
            - pipelineRef
            - url
            type: object
          status:
            description: RepositoryStatus defines the observed state of Repository
            properties:
              lastError:
                type: string
              observedGeneration:
                format: int64
                type: integer
              pollStatus:
                description: PollStatus represents the last polled state of the repo.
                properties:
                  etag:
                    type: string
                  ref:
                    type: string
                  sha:
                    type: string
                required:
                - etag
                - ref
                - sha
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
